spring:
  application:
    name: emailSender

  mail:
    host: smtp.gmail.com
    port: 587
    username: saravanandurai938@gmail.com
    password: ghbv udin lfvd nvoi

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}